name: Build Verification

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Run mypy
      run: |
        source .venv/bin/activate
        mypy .

    - name: Run Black check
      run: |
        source .venv/bin/activate
        black . --check

    - name: Run Pylint
      run: |
        source .venv/bin/activate
        pylint app tests

    - name: Run Pytest
      run: |
        source .venv/bin/activate
        pytest --tb=short --disable-warnings
